version: "3.7"

services:
  frontend:
    container_name: frontend
    restart: always
    depends_on:
      - server
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    command: yarn start
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend:/usr/src/app/frontend
    ports:
      - "3000:3000"
    links:
      - server
  server:
    container_name: server
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    command: npm start
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/atm_project
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=atm_project
    ports:
      - "27017:27017"
