FROM node:10

WORKDIR /usr/src/app/server

COPY package*.json /usr/src/app/server/

RUN npm install

RUN wget -O - http://apt.pm-codeworks.de/pm-codeworks.de.gpg | apt-key add - 

RUN wget http://apt.pm-codeworks.de/pm-codeworks.list -P /etc/apt/sources.list.d/

RUN apt-get update 

RUN apt-get install python-fingerprint --yes

RUN apt-get -f install

COPY . /usr/src/app/server/

EXPOSE 3001

CMD ["npm", "start" ] 